### ISSUE TITLE
Can you not avoid using MATLAB ?!

### ISSUE THREAD

**Issue by Tetsujinfr** [hszhao/ICNet#12]
any way I can use this without having the beloved MATLAB?
I love so much closed source that I am really close to buy a licence but hey ... no actually.

**Comment by xhsoldier** [comment]
I have changed to python, but can only input 1025*2049 size image, other size image does not work.

**Comment by Tetsujinfr** [comment]
Hi
Where is your code, can I have a look? That is strange that it would not work for other sizes but 1024x2048 is an interesting resolution anyway.

**Comment by elkestc** [comment]
I am struggling with converting to Python right now. Would be pleased to have a glance at your code.
Thank you very much.

**Comment by hellochick** [comment]
Hey @AnastasiaAz @Tetsujinfr , I have converted ICNet from caffe into tensorflow, you can take a look on https://github.com/hellochick/ICNet_tensorflow

**Comment by elkestc** [comment]
> Hey @AnastasiaAz @Tetsujinfr , I have converted ICNet from caffe into tensorflow, you can take a look on https://github.com/hellochick/ICNet_tensorflow

Hey @hellochick, many thanks! I'm checking it.

**Comment by Tetsujinfr** [comment]
Amazing, you are a star. Got the inference workin in two minutes and no Matlab! 

Closing the issue and putting a star to your python conversion Git.

Tets
