### ISSUE TITLE
Train architecture

### ISSUE THREAD

**Issue by melgor** [hszhao/ICNet#14]
Could you provide train architecture? I want to implement your idea at TensorFlow, but I cannot get your idea of network only using information from paper.
There are lacking information like:
1. Number of filters in each layer, especially in pipeline image/4/
2. I released prototxt I do not see any image/4 as input, where it go?
3.  I see that you are using residuals, are they the same like in PSPNet?

I was using this visualization as [base](http://ethereon.github.io/netscope/#/gist/240988d33f1ae2909d997fd5e09d81ad), but I'm not able to match this architecture with that from pipeline.

**Comment by hellochick** [comment]
@melgor  Hey, you can take a look at my reproduced model, it can work and get nice result. Maybe it can help you to develop! model link: 
https://github.com/hellochick/ICNet-tensorflow/blob/master/model.py
